# Generated by Django 6.0.7 on 2026-07-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_code", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=500)),
                ("ordem", models.IntegerField()),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capitulos",
                        to="regulations.documento",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "unique_together": {("documento", "id_code")},
            },
        ),
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_code", models.CharField(max_length=30)),
                ("titulo", models.CharField(blank=True, default="", max_length=500)),
                ("texto", models.TextField()),
                ("ordem", models.IntegerField()),
                (
                    "relacionados",
                    models.ManyToManyField(blank=True, to="regulations.artigo"),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artigos",
                        to="regulations.capitulo",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "unique_together": {("capitulo", "id_code")},
            },
        ),
    ]
