# Generated by Django 6.0.7 on 2026-07-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('posicoes', models.JSONField(blank=True, default=dict)),
                ('ementa', models.TextField(blank=True, default='')),
                ('preambulo', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Disposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gerais', 'Disposições Gerais'), ('transitorias', 'Disposições Transitórias'), ('finais', 'Disposições Finais')], max_length=20)),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposicoes', to='regulations.documento')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parte', 'Parte'), ('livro', 'Livro'), ('titulo', 'Título'), ('capitulo', 'Capítulo'), ('secao', 'Seção'), ('subsecao', 'Subseção')], max_length=10)),
                ('rotulo', models.CharField(blank=True, default='', max_length=50)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('ordem', models.IntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='regulations.documento')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='regulations.estruturabloco')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=30)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('texto', models.TextField(blank=True, default='')),
                ('caput', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField()),
                ('relacionados', models.ManyToManyField(blank=True, to='regulations.artigo')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='regulations.estruturabloco')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Inciso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=20)),
                ('texto', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incisos', to='regulations.artigo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Alinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10)),
                ('texto', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('inciso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineas', to='regulations.inciso')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10)),
                ('texto', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('alinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='regulations.alinea')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(blank=True, default='', max_length=50)),
                ('texto', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='regulations.artigo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='inciso',
            name='paragrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incisos', to='regulations.paragrafo'),
        ),
    ]
