# Generated by Django 6.0.7 on 2026-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='posicoes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
